apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-deployment
  labels:
    app: orderapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: isaacd2/orderapi:amd64
        ports:
        - containerPort: 3000