apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  labels:
    app: orderapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: isaacd2/orderapi:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      volumes:
        - name: orderapi-volume
          persistentVolumeClaim:
            claimName: orderapi-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderapi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      ephemeral-storage: "1Gi"
  storageClassName: standard-rwx
