version: 2.1
orbs:
  docker: circleci/docker@3.0.1
  gke: circleci/gcp-gke@2.1.0
  gcp-cli: circleci/gcp-cli@3.0.0

jobs:
  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - gcp-cli/setup:
          components: "gke-gcloud-auth-plugin kubectl"
      - gke/update-kubeconfig-with-credentials:
          cluster: "orderapi"
      - run:
          name: Update Deployment
          command: |
            kubectl set image deployment/orderapi \
              orderapi=isaacd2/orderapi:amd64

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: isaacd2/orderapi
          tag: amd64
      - deploy:
          requires:
            - docker/publish
