version: 2.1
orbs:
  docker: circleci/docker@3.0.1
  gke: circleci/gcp-gke@2.1.0

jobs:
  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - gke/install
      - gke/update-kubeconfig-with-credentials:
          cluster: "orderapi"
          install-kubectl: true
          perform-login: true
      - run:
          name: Update Deployment
          command: |
            kubectl set image deployment/orderapi \
              orderapi=isaacd2/orderapi:amd64

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: isaacd2/orderapi
          tag: amd64
          remote_docker_dlc: true
          use_remote_docker: true
      - deploy:
          requires:
            - docker/publish
