version: 2.1
orbs:
  docker: circleci/docker@3.0.1
jobs:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          executor:
            image: circleci/node
            name: docker/docker
            tag: boron-browsers
          image: isaacd2/orderapi
          remote_docker_dlc: true
          tag: amd64
          use_remote_docker: true
  deploy:
    machine: true
    steps:
      - checkout
      - gke/install
      - gke/update-kubeconfig-with-credentials:
          cluster: "orderapi"
          install-kubectl: true
          perform-login: true
      - run:
          name: Update Deployment
          command: |
            kubectl set image deployment/orderapi \
              orderapi=isaacd2/orderapi:amd64
workflows:
  build-and-deploy:
    jobs:
      - build-and-publish-docker-image
      - deploy:
          requires:
            - build-and-publish-docker-image